### ISSUE TITLE
Add metadata to src-stats.yaml

### ISSUE THREAD

**Issue by tim-band** [SAFEHR-data/datafaker#15]
The `src-stats.yaml` file reports the outputs of queries, looking like so:

```yaml
query1:
- value1: 1.01
  value2: 2.02
query2:
- valueA: 26.01
  valueB: 27.02
  valueC: 28.03
```

The metadata we want is:
- The query that generated these values
- The DP information
- A timestamp

This will help us understand what the data mean, and whether we want to keep or regenerate some of it (as later work)

The easiest way to add metadata is probably like so:

```yaml
query1:
- _metadata:
  - query: SELECT ...
    dp-query: SELECT value1, value2 ...
    epsilon: 0.01
    delta: 1e-6
    snsql-metadata:
    - max_ids: 1
      ...
  value1: 1.01
  value2: 2.02
```
